from __future__ import annotations


VISUAL_LABELS = [
    "people",
    "portrait",
    "family",
    "friends",
    "children",
    "man",
    "woman",
    "team",
    "crowd",
    "office",
    "workspace",
    "meeting room",
    "conference",
    "laptop",
    "computer screen",
    "smartphone",
    "technology",
    "city",
    "street",
    "building",
    "architecture",
    "home interior",
    "kitchen",
    "bedroom",
    "living room",
    "restaurant",
    "coffee shop",
    "food",
    "drink",
    "dessert",
    "fruit",
    "vegetables",
    "fashion",
    "clothing",
    "shoes",
    "jewelry",
    "car",
    "bicycle",
    "airplane",
    "train",
    "boat",
    "beach",
    "ocean",
    "mountain",
    "forest",
    "park",
    "garden",
    "flower",
    "animal",
    "dog",
    "cat",
    "bird",
    "horse",
    "sports",
    "fitness",
    "running",
    "basketball",
    "soccer",
    "travel",
    "vacation",
    "wedding",
    "celebration",
    "concert",
    "art",
    "painting",
    "night scene",
    "sunset",
    "sunrise",
    "water",
    "snow",
    "desert",
    "close-up product",
    "luxury",
    "minimal",
    "bright lighting",
    "dark lighting",
    "outdoor",
    "indoor",
    "business",
    "education",
    "healthcare",
]


COLOR_WORDS = [
    "red",
    "orange",
    "yellow",
    "green",
    "blue",
    "purple",
    "pink",
    "brown",
    "black",
    "white",
    "gray",
    "gold",
]
